import pandas as pd

csv_path = r"C:\snifflab\snifflab\data\fragrances.csv"

new_rows = [
    {
        "url": "",
        "Perfume": "dulce-de-leche",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "almond\t hazelnut",
        "Middle": "coumarin\t sweet cream\t caramel",
        "Base": "vanilla\t amber\t white musk",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "gourmand",
        "mainaccord2": "sweet",
        "mainaccord3": "vanilla",
        "mainaccord4": "creamy",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "sahara-sunset",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "amalfi lemon\t marigold\t bergamot\t black currant",
        "Middle": "violet\t cyclamen\t jasmine",
        "Base": "vetiver\t musk\t amber\t virginia cedar",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "citrus",
        "mainaccord2": "floral",
        "mainaccord3": "woody",
        "mainaccord4": "fresh",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "invicto",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "pineapple\t bergamot\t pink pepper",
        "Middle": "birch\t patchouli\t jasmine",
        "Base": "musk\t ambergris\t oakmoss",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "fruity",
        "mainaccord2": "woody",
        "mainaccord3": "fresh",
        "mainaccord4": "musky",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "let-them-eat-cake",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "bitter almond\t milk\t nutella\t malt\t lily",
        "Middle": "cake accord\t brandy\t vanilla\t custard\t brown sugar\t tonka bean\t benzoin\t clover",
        "Base": "incense\t gunpowder\t bran\t styrax\t tolu balsam\t papyrus",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "gourmand",
        "mainaccord2": "sweet",
        "mainaccord3": "dessert",
        "mainaccord4": "vanilla",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "havana-vanilla",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "tobacco leaf\t spicy notes",
        "Middle": "vanilla\t tobacco blossom\t cacao",
        "Base": "tonka bean\t dried fruits\t woods",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "vanilla",
        "mainaccord2": "warm spicy",
        "mainaccord3": "tobacco",
        "mainaccord4": "sweet",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "baked-in-capri",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "lemon zest\t rum",
        "Middle": "whipped cream\t praline\t butter",
        "Base": "bourbon vanilla\t brown sugar",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "gourmand",
        "mainaccord2": "citrus",
        "mainaccord3": "sweet",
        "mainaccord4": "dessert",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "light-of-rome",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "blackcurrant\t pink pepper\t bergamot",
        "Middle": "jasmine sambac\t jasmine tea",
        "Base": "bourbon vanilla\t cashmeran\t guaiac wood",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "vanilla",
        "mainaccord2": "floral",
        "mainaccord3": "sweet",
        "mainaccord4": "woody",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "glamour-girl",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "almond\t coffee\t bergamot\t lemon",
        "Middle": "tuberose\t bulgarian rose\t orris",
        "Base": "tonka bean\t vanilla\t sandalwood",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "floral",
        "mainaccord2": "sweet",
        "mainaccord3": "warm spicy",
        "mainaccord4": "vanilla",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "love-allure",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "neroli\t bergamot",
        "Middle": "orange blossom\t jasmine\t marshmallow",
        "Base": "vanilla\t caramel\t musk",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "sweet",
        "mainaccord2": "marshmallow",
        "mainaccord3": "floral",
        "mainaccord4": "vanilla",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "golden-nectar",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "cognac",
        "Middle": "cinnamon\t tonka bean\t oak",
        "Base": "vanilla\t praline\t sandalwood\t almond",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "sweet",
        "mainaccord2": "boozy",
        "mainaccord3": "gourmand",
        "mainaccord4": "vanilla",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "cherry-elixir",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "cherry\t bitter almond\t cinnamon",
        "Middle": "plum\t turkish rose\t jasmine",
        "Base": "vanilla\t tonka bean\t balsam",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "cherry",
        "mainaccord2": "sweet",
        "mainaccord3": "fruity",
        "mainaccord4": "gourmand",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "portanera",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "bergamot\t mandarin orange\t lemon\t bitter orange\t lavender\t rosemary",
        "Middle": "african orange flower\t neroli\t jasmine",
        "Base": "amber\t angelica\t ambrette",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "citrus",
        "mainaccord2": "aromatic",
        "mainaccord3": "fresh",
        "mainaccord4": "white floral",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "coastal-woods",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "fig tree\t grapefruit",
        "Middle": "marine notes\t ambrette",
        "Base": "clary sage\t amberwood",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "marine",
        "mainaccord2": "woody",
        "mainaccord3": "fresh",
        "mainaccord4": "aromatic",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "floral-explosion",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "green tea\t bergamot\t osmanthus",
        "Middle": "white flowers\t orchid\t rose",
        "Base": "patchouli\t musk\t vanilla",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "floral",
        "mainaccord2": "sweet",
        "mainaccord3": "patchouli",
        "mainaccord4": "musky",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "stormlight",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "pear\t bergamot\t mandarin orange\t ginger",
        "Middle": "orange blossom\t georgywood",
        "Base": "musk\t ambrofix\t akigalawood\t cedar",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "fresh",
        "mainaccord2": "citrus",
        "mainaccord3": "woody",
        "mainaccord4": "musky",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "sundara",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "pistachio\t bergamot\t cardamom\t pink pepper",
        "Middle": "tuberose\t ylang-ylang\t jasmine",
        "Base": "coconut\t amber\t tonka bean\t benzoin",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "tropical",
        "mainaccord2": "creamy",
        "mainaccord3": "floral",
        "mainaccord4": "warm spicy",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "emberus",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "mango\t ginger\t lemon",
        "Middle": "pear\t jasmine\t cedar\t orange blossom",
        "Base": "musk\t ambrofix\t agarwood\t amber",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "fruity",
        "mainaccord2": "woody",
        "mainaccord3": "amber",
        "mainaccord4": "fresh",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "dont-cry-over-spilt-milk",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "milk\t strawberry\t forest fruits",
        "Middle": "powdery notes",
        "Base": "caramel\t wood notes",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "sweet",
        "mainaccord2": "milky",
        "mainaccord3": "gourmand",
        "mainaccord4": "fruity",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "dark-seduction",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "pear\t orange blossom",
        "Middle": "jasmine\t coffee\t bitter almond\t licorice",
        "Base": "vanilla\t cashmere wood\t cedar",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "coffee",
        "mainaccord2": "vanilla",
        "mainaccord3": "sweet",
        "mainaccord4": "warm spicy",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "visionnaire",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "citron\t bergamot\t sicilian orange",
        "Middle": "neroli\t ginger\t ceylon cinnamon",
        "Base": "black tea\t ambroxan\t guaiac wood\t olibanum",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "citrus",
        "mainaccord2": "tea",
        "mainaccord3": "fresh",
        "mainaccord4": "woody",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "voltaire",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "cinnamon\t orange blossom\t cardamom",
        "Middle": "bourbon vanilla\t elemi\t praline",
        "Base": "tonka bean\t candied almond\t ambroxan",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "sweet",
        "mainaccord2": "vanilla",
        "mainaccord3": "warm spicy",
        "mainaccord4": "amber",
        "mainaccord5": ""
    },
    {
        "url": "",
        "Perfume": "marzipan-brulee",
        "Brand": "desmirage",
        "Country": "",
        "Gender": "",
        "Rating Value": 0,
        "Rating Count": 0,
        "Year": "",
        "Top": "marzipan\t almond",
        "Middle": "creme brulee\t vanilla\t sugar",
        "Base": "marshmallow\t benzoin\t musk",
        "Perfumer1": "",
        "Perfumer2": "",
        "mainaccord1": "gourmand",
        "mainaccord2": "marzipan",
        "mainaccord3": "vanilla",
        "mainaccord4": "sweet",
        "mainaccord5": ""
    },
]

df = pd.read_csv(csv_path, sep=";", encoding="latin1")

new_df = pd.DataFrame(new_rows)

# make sure columns match the file exactly
for col in df.columns:
    if col not in new_df.columns:
        new_df[col] = ""

new_df = new_df[df.columns]

combined = pd.concat([df, new_df], ignore_index=True)
combined.to_csv(csv_path, sep=";", index=False, encoding="latin1")

print("Done. Added 22 desmirage fragrances.")