[theme]
base="light"
primaryColor="#A1005A"
backgroundColor="#FFF5FB"
secondaryBackgroundColor="#FFE0F1"
textColor="#4A1030"
borderColor="#F39ACB"
showWidgetBorder=true
baseRadius="0.85rem"
buttonRadius="0.85rem"

[theme.sidebar]
backgroundColor="#FFD9EE"
secondaryBackgroundColor="#FFF0F8"
textColor="#4A1030"
primaryColor="#6F003D"
borderColor="#F39ACB"
showWidgetBorder=true
baseRadius="0.85rem"
buttonRadius="0.85rem"